apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dr-docso.fullname" . }}
  labels:
    {{- include "dr-docso.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "dr-docso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dr-docso.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-config
        image: "busybox:1.37"
        command:
          - cp
          - -n
          - /config/config.json 
          - /data/config.json"
        volumeMounts:
          - name: data
            mountPath: /data
          - name: config
            mountPath: /config
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          - name: data
            mountPath: /docso
        env:
          - name: BOT_TOKEN
            valueFrom:
              secretKeyRef:
              {{- if .Values.existingSecret }}
                name: "{{ .Values.existingSecret }}"
              {{- else }}
                name: {{ include "dr-docso.fullname" . }}
              {{- end }}
                key: token
      volumes:
        - name: config
          configMap:
            name: {{ include "dr-docso.fullname" . }}-configmap
        - name: "data"
          persistentVolumeClaim:
            claimName: "dr-docso"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
