{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dr-docso.fullname" . }}
  labels:
    {{- include "dr-docso.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.botToken | required "botToken is required" | b64enc }}
{{- end -}}