apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dr-docso
spec:
  accessModes:
    - "ReadWriteOnce"
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName}}
  {{- end }}
  resources:
    requests:
      storage: 1Gi
