name: CI/CD
on:
  push:
  release:
    types: [created]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: checkout code
      uses: actions/checkout@v2
    - name: go fmt
      run: test -z "$(gofmt -e -d -s . | tee /dev/stderr)"
    - name: go vet
      run: go vet ./...
    - name: go build
      run: go build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        name: dr-docso-binary
        path: dr-docso
        retention-days: 5
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run chart-releaser
      if: github.event_name == 'release' && github.event.action == 'created'
      uses: helm/chart-releaser-action@v1.5.0
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"