name: CI/CD
on:
  push:
  release:
    types: [created]

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: checkout code
      uses: actions/checkout@v2
    - name: go fmt
      run: test -z "$(gofmt -e -d -s . | tee /dev/stderr)"
    - name: go vet
      run: go vet ./...
    - name: go build
      run: go build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: github.event_name == 'release' && github.event.action == 'created'
      with:
        name: dr-docso-binary
        path: dr-docso
        retention-days: 5
  release:
    needs: codestyle
    runs-on: [self-hosted, swiltink]
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dr-docso-binary
      - name: release
        run: sudo docso-release dr-docso